# Generated by Django 5.0.6 on 2024-07-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainApp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('username', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('pin', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('password', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('otp', models.IntegerField(blank=True, default=9241, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
    ]
