# Generated by Django 5.0.6 on 2024-07-29 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='uploads')),
                ('education', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('skills', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('internship', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('experience', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('project', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('video', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
            ],
        ),
    ]
