# Generated by Django 5.0.6 on 2024-08-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
